/* eslint-disable */
// @ts-nocheck
// Generated by unplugin-vue-components
// Read more: https://github.com/vuejs/core/pull/3399
// biome-ignore lint: disable
export {}

/* prettier-ignore */
declare module 'vue' {
  export interface GlobalComponents {
    IconCustomAPlay: typeof import('~icons/custom/a-play')['default']
    IconCustomHorizontal: typeof import('~icons/custom/horizontal')['default']
    IconCustomLogo: typeof import('~icons/custom/logo')['default']
    IconCustomPlay: typeof import('~icons/custom/play')['default']
    IconCustomShuffle: typeof import('~icons/custom/shuffle')['default']
    IconCustomStop: typeof import('~icons/custom/stop')['default']
    IconCustomVertical: typeof import('~icons/custom/vertical')['default']
    NButton: typeof import('naive-ui')['NButton']
    NCard: typeof import('naive-ui')['NCard']
    NDataTable: typeof import('naive-ui')['NDataTable']
    NotificationType: typeof import('naive-ui')['NotificationType']
    NSpace: typeof import('naive-ui')['NSpace']
    RouterLink: typeof import('vue-router')['RouterLink']
    RouterView: typeof import('vue-router')['RouterView']
    TButton: typeof import('tdesign-vue-next')['Button']
    TCard: typeof import('tdesign-vue-next')['Card']
    TCol: typeof import('tdesign-vue-next')['Col']
    TConfigProvider: typeof import('tdesign-vue-next')['ConfigProvider']
    TDateRangePicker: typeof import('tdesign-vue-next')['DateRangePicker']
    TRow: typeof import('tdesign-vue-next')['Row']
    TSpace: typeof import('tdesign-vue-next')['Space']
    TTButton: typeof import('tdesign-vue-next')['TButton']
  }
}
